### ISSUE TITLE
Bad File Coursera Quiz

### ISSUE THREAD

**Issue by pk86pk86** [HopkinsIDD/ConTESSA#16]
File name:  contessa-inputs-module2.yaml

Error Message in ConTESSA:  

UPLOAD FAILED. Input file must be a .yaml 
file previously downloaded from this application.

Problem:  Could not complete ConTESSA: Interactive Tool to Estimate Impact of Contact Tracing
Graded Quiz • 20 min

Please advise.

**Comment by LucyMcGowan** [comment]
Was the file contessa-inputs-module2.yaml downloaded from the application?

**Comment by pk86pk86** [comment]
No. The link is in the coursera quiz. I downloaded it to my hard drive and then attempted to “load” it into the application using the “browse” button.  I attempted all of the above several times.

I cannot continue or complete the course without this. Please advise.

Many thanks, pk

Philip Kay
t. +1.212.234.5909
pk86@columbia.edu 
www.philipkay.org

**Comment by pk86pk86** [comment]
Dear Dr. McGowan,

I have an interview for a management position with a contact tracing program tomorrow and am very eager to complete your course before that.  This technical glitch (see below) is preventing me from doing that.  There doesn’t appear to be any way to access the file from within the application.  I would be happy to provide screenshots and additional details as necessary. 

Thanks for your prompt attention.  pk

Philip Kay
pk86@columbia.edu
+1.212.234.5909

**Comment by LucyMcGowan** [comment]
Can you open the .yaml file you have downloaded and paste the first few lines here? I am not able to reproduce your error at the moment but I am happy to help you troubleshoot.

**Comment by LucyMcGowan** [comment]
(you can open a .yaml file in most simple text editors)

**Comment by pk86pk86** [comment]
Here are the complete contents. (It’s not that long.)  Thanks again, pk

pass_test: Day 5
  n_isolate_a: 5625
  omega_c: 50
  n_isolate_b: 5625
  log_scale: no
  tabs: dash
  ifr: '0.75'
  mult: 0.5
  comm_quar_a: Day 10
  nu_b: 6
  n_deaths_b: 100
  t_pa_b: Day 7
  pass_isol2:
  - Day 5
  - Day 7
  generation_b: '3'
  omega_c_a: 50
  comm_quar: Day 10
  omega_h: 70
  advanced_tab: 0
  load: ~
  pass_isol_b: Day 7
  pass_isol3:
  - Day 5
  - Day 7
  alpha_b: 1
  save_name: 1
  surv: 0
  n_infect_calc_a: direct
  kappa: 0.5
  kappa_b: 0.5
  scenario_b: no
  n_isolate: 5625
  n_deaths_a: 100
  pass_isol_a: Day 7
  house_quar: Day 9
  advanced_tab2: 0
  nu: 6
  n_detect_b: 6250
  n_detect_quar_b: 5625
  n_detect_a: 6250
  contact_c_b: 3
  mult_b: 0.5
  word: word
  R: 2.5
  ifr_other_b: 0.75
  R_b: 2.5
  save_server: no
  prop_detect: 25
  next_dash: 0
  n_detect: 6250
  n_infect_calc_b: direct
  pass_isol:
  - Day 5
  - Day 7
  n_detect_quar: 5625
  contact_h: 3
  sidebarItemExpanded: ~
  advanced_tab3: 0
  n_infect_calc: direct
  contact_c: 3
  get_report: 0
  report_name: contessa-report
  contact_c_a: 3
  t_pa: Day 7
  omega_c_b: 70
  alpha: 1
  omega_h_a: 70
  return: 1
  ifr_other_a: 0.75
  next_comm: 0
  name: The Shire
  prop_detect_a: 25
  prepared_by: ''
  n_deaths: 100
  ifr_other: 0.75
  file_name: contessa-inputs
  ifr_a: '0.75'
  comm_quar_b: Day 10
  n_detect_quar_a: 5625
  sidebarCollapsed: no
  ifr_b: '0.75'
  generation: '3'
  next_house: 0
  plots: 0
  omega_h_b: 70
  contact_h_a: 3
  contact_h_b: 3
  house_quar_b: Day 9
  house_quar_a: Day 9
  prop_detect_b: 25
  update_b: 0

Philip Kay
pk86@columbia.edu
+1.212.234.5909

**Comment by LucyMcGowan** [comment]
Ah ok, I see this issue. For a quick fix, please edit `t_pa` to be `t_da` and `t_pa_b` to be `t_da_b` in your .yaml file. This is a bug in the quiz itself - I will push a global fix soon, changing the .yaml file itself should work for you - please let me know if not.

**Comment by pk86pk86** [comment]
Yes, that appears to have done the trick.  S1 reads as 6,250.  Please confirm.

Many Thanks,  pk

Philip Kay
pk86@columbia.edu
+1.212.234.5909

**Comment by LucyMcGowan** [comment]
Yep! Glad it worked. I will push the global update tonight (which means if you complete the quiz again after tomorrow, for example, you should use the *original* file with `t_pa` and `t_pa_b` as the variable names. A fresh download of the .yaml from the quiz at the time will also work.)

**Comment by pk86pk86** [comment]
Hi Dr. McGowan,

More problems with this file/quiz, I’m afraid:

1:  The first item on question 5 reads:  "Reducing the delay to quarantine of household contacts, such that household contacts are on average quarantined on the same day as the case is isolated, 7 days after symptom onset of the case.”  But the loaded file indicates only 5 days after symptom onset and 6 for the household contacts.  There appears to be a discrepancy here.

2.  In adjusting one of the variables, I failed to take note of the original setting to change it back to.  But when I closed out and tried to reload the corrected file I couldn’t. I get the same error message of “upload failed."  

When I try to download the module2 inputs file from the server anew I now get the following error message:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access denied</Message>
</Error>

This is just for your information.  My interview tomorrow was rescheduled, so I’m going to resume the course once you’ve had a chance to make the necessary fixes.  I’d be grateful if you could let me know when the corrected file is available online.

Thanks again,  pk


Philip Kay
pk86@columbia.edu
+1.212.234.5909

**Comment by LucyMcGowan** [comment]
Please see my responses below in **bold**.

1:  The first item on question 5 reads:  "Reducing the delay to quarantine of household contacts, such that household contacts are on average quarantined on the same day as the case is isolated, 7 days after symptom onset of the case.”  But the loaded file indicates only 5 days after symptom onset and 6 for the household contacts.  There appears to be a discrepancy here.

**The file works correctly for me. Please re-download the file from the Coursera Quiz (do not update the variable, `t_pa` and `t_pa_b` should now work, a fix was pushed last night)**

2.  In adjusting one of the variables, I failed to take note of the original setting to change it back to.  But when I closed out and tried to reload the corrected file I couldn’t. I get the same error message of “upload failed."

**This is likely due to using the file where the variable names were updated from yesterday - this has been fixed in the current application to take the file downloaded from the Quiz**

When I try to download the module2 inputs file from the server anew I now get the following error message:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access denied</Message>
</Error>

**Are you seeing this on the Coursera site? I was just able to download the file without this error - perhaps you need to sign back in?**

**Comment by pk86pk86** [comment]
Thank you for your help. I was able to complete the course successfully.  pk

Philip Kay
pk86@columbia.edu
+1.212.234.5909
